name: Kits
main: com.endercraftservers.geekygamer14.KitPlugin
version: 1.0
commands:
  kit:
    description: Get the VIP kit.
    usage: /kit
    permission: kits.kit
    permission-message: "You do not have permission to use Kits!"