name: Kits
main: com.endercraftservers.geekygamer14.KitPlugin
version: 1.0
commands:
  kit:
    description: Get the VIP kit.
    usage: /vipkit
    permission: kits.vip
    permission-message: You must have VIP status to get this kit!